# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8d2b7038ebc13414827f745a04507c30e76d7801e6ffb76d6f0d834745c39da17f3030864b07b8818a1a556e737ff5ede37887f34199409c030b73d7509499b5

test:
  secret_key_base: e64910b3b876b3ad8bb09f6f71f248b5154a63291aa444add026bcab83622347a797df0116e047a0540615316442b81d5b4439ecdb87d308962c2470ea4b5168

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
